feat add AirPlayIconButton widget, it use a default IconTheme
MrJai/flutter_to_airplay pull request #17
Opened 2022-02-25 11:46 UTC by SimoneBressan

- feat add AirPlayIconButton widget, it use a default IconTheme
- feat add onShowPickerView and onClosePickerView to AirPlayRoutePickerView
- Arranged the files inside the library and exposed a name for the library

2022-02-25 13:22 UTC, GabM3 requested changes

2022-02-25 13:22 UTC, GabM3 commented on ios/Classes/FlutterRoutePickerView.swift
> +            }
else?? nothing?
```suggestion
            if #available(iOS 13.0, *) {
                tempView.prioritizesVideoDevices = arguments["prioritizesVideoDevices"] as? Bool ?? false
            }
```

2022-02-25 14:53 UTC, MrJai commented
That's good work @SimoneBressan. Thanks for your contribution.
I will merge and upload a new version in a day.

2022-08-19 15:22 UTC, vanlooverenkoen commented
@SimoneBressan any idea when you could pick up this pull request?

2023-04-18 11:19 UTC, roman800 commented
Is it only the changelog.md that is missing for this pr to be complete ? 
Could really use the onShowPickerView and onClosePickerView for the AirPlayRoutePickerView for my project 🙏

2023-04-19 13:17 UTC, SimoneBressan commented
@MrJai Updated Changelog and fixed color management

2023-04-19 13:18 UTC, MrJai commented
I will review and release a new version today.

2023-04-19 14:38 UTC, merged

2023-04-19 18:06 UTC, MrJai commented
The new version is published. Thank you @SimoneBressan for your contribution!